theme: jekyll-theme-minimal
title: ITLCT Research Blog
description: Unified Framework for Information-Time-Life-Consciousness
show_downloads: false
google_analytics:

# 基础 URL
baseurl: /chronos-blog
url: https://sandmark78.github.io

# Permalink 设置
permalink: /:year/:month/:day/:title/
markdown: kramdown

# 默认值
defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: default