theme: jekyll-theme-minimal
title: ITLCT Research Blog
description: Unified Framework for Information-Time-Life-Consciousness
show_downloads: false
google_analytics:

# 基础 URL
baseurl: /chronos-blog
url: https://sandmark78.github.io

# Markdown 配置
markdown: kramdown

# 默认值
defaults:
  - scope:
      path: "_posts"
    values:
      layout: default
      permalink: /posts/:title/
